### PR TITLE
rebased fix for trace decorator

### PR DESCRIPTION
**Pull request by abadger**

### CODE REVIEW

**Comment by mithro** [comment]
Got an example of what this is fixing?

**Comment by abadger** [comment]
Hey @mithro Here's a rebased version of my PR against zestyping's repo: https://github.com/zestyping/q/pull/11 (issue https://github.com/zestyping/q/issues/10 )

It fixes the trace decorator not giving proper trace results if you use @q.

Here's some tests:

``` python
import q

def something(func):
    def do_nothing(*args, **kwargs):
        return func(*args, **kwargs)
    return do_nothing

@q
def log(msg='default'):
    return msg

@q.t
def sudo_log(msg='default'):
    return msg

@something
@q
@something
def decorated_log(msg='default'):
    return msg

log('me a message')
sudo_log('sudo a message')
decorated_log('decorated message')
```

```
Output without the PR:

 0.0s <module>: <function log>
 0.0s <module>: <function do_nothing>
 0.0s sudo_log('sudo a message')
 0.0s -> 'sudo a message'
```

Output with the PR:

```
 0.0s log('me a message')
 0.0s -> 'me a message'
 0.0s sudo_log('sudo a message')
 0.0s -> 'sudo a message'
 0.0s do_nothing('decorated message')
 0.0s -> 'decorated message'
```

The last example could be improved to show the original function but this is already an improvement of the status quo.

**Comment by abadger** [comment]
Looking at how we might print the original function's name more, I've come to the conclusion that in python it's the responsibility of the individual decorators to either do that or not.   Michele Simionato has a nice writeup of the problem: http://micheles.googlecode.com/hg/decorator/documentation.html#statement-of-the-problem

Here's an updated decorated case:

``` python
import q
import functools

def something(func):
    def do_nothing(*args, **kwargs):
        return func(*args, **kwargs)
    return functools.update_wrapper(do_nothing, func)

@something
@q
@something
def decorated_log(msg='default'):
    return msg

decorated_log('decorated message')
```

**Comment by mithro** [comment]
I have merged this change into my https://github.com/mithro/q/tree/abadger-fix branch and added tests.

Will merge the code upstream shortly.

**Pull request closed without merging**
